[project]
name = "learning-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "ipython>=9.5.0",
    "numpy>=2.3.3",
    "scikit-learn>=1.7.2",
    "torchvision>=0.23.0",
]
